name: Create Issue
on:
  workflow_call:
    inputs:
      assignees:
        required: true
        type: string
      commit_hash:
        required: true
        type: string
      owner_repository:
        required: true
        type: string
      issue_template:
        required: true
        type: string
      branch_name:
        required: true
        type: string
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create issue if failed
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_HASH: ${{ inputs.commit_hash }}
          OWNER_REPOSITORY: ${{ inputs.owner_repository }}
          BRANCH_NAME: ${{ inputs.branch_name }}
        with:
          assignees: ${{ inputs.assignees }}
          filename: ${{ inputs.issue_template }}
