name: Generate Repo Meta
on:
  workflow_call:
    outputs:
      image_tag:
        description: "The container image's tag"
        value: ${{ jobs.repo-meta.outputs.IMAGE_TAG }}
      repository_name:
        description: "The container repository's name"
        value: ${{ jobs.repo-meta.outputs.REPO_NAME }}
jobs:
  repo-meta:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.container-image.outputs.IMAGE_TAG }}
      repo_name: ${{ steps.repository-name.outputs.REPO_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract repository's name
        id: repository-name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_OUTPUT

      - name: Create image tag
        id: container-image
        run: |
          BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's/\//_/g')
          IMAGE_TAG=${{ github.sha }}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
