name: Manage Supply Chain
on:
  workflow_call:
    inputs:
      image_digest:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      repository_name:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true
jobs:
  sign-attest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      IMAGE_REF: docker.io/${{ secrets.docker_username }}/${{ inputs.repository_name }}@${{ inputs.image_digest }}
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3

    - name: Install Syft
      uses: anchore/sbom-action/download-syft@v0.15.4

    - name: Generate CycloneDX SBOM
      run: |
        syft scan "$IMAGE_REF" -o cyclonedx-json > sbom.cdx.json

    - name: Sign image
      run: |
        cosign sign --yes "$IMAGE_REF"

    - name: Attest SBOM
      run: |
        cosign attest --yes \
          --predicate sbom.cdx.json \
          --type cyclonedx \
          "$IMAGE_REF"

    - name: Verify Signature
      run: |
        cosign verify \
          --certificate-identity-regexp "https://github\.com/${{ github.workflow_ref }}" \
          --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
          "$IMAGE_REF"

    - name: Verify Attestation
      run: |
        cosign verify-attestation \
          --type cyclonedx \
          --certificate-identity-regexp "https://github\.com/${{ github.workflow_ref }}" \
          --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
          "$IMAGE_REF"