name: Run Unit Tests
on:
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go_version }}

    - name: Vet source code
      run: |
        go vet ./...

    - name: Run unit tests
      run: |
        go test ./...
