name: Run Static Analysis
on:
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go_version }}

    - name: Run linter
      uses: golangci/golangci-lint-action@v6
