name: Service CI
on:
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string
      helm_version:
        required: true
        type: string
      helm_folder:
        required: false
        type: string
        description: "The folder that composes the Helm Chart, default is app"
        default: "app"
      unittest_issue_label:
        required: false
        type: string
        default: "bug"
      unittest_issue_title:
        required: false
        type: string
        default: "Unit Testing failed"
      linting_issue_label:
        required: false
        type: string
        default: "technical debt"
      linting_issue_title:
        required: false
        type: string
        default: "Code Linting failed"
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true
      helm_repo_url:
        required: true
      helm_repo_pat:
        required: true
      helm_repo_target:
        required: true
      helm_repo_owner:
        required: true
      helm_repo_name:
        required: true
      sonar_token:
        required: true

jobs:
  unit-tests:
    uses: hasAnybodySeenHarry/workflows/.github/workflows/run-unit-tests.yaml@main
    with:
      go_version: ${{ inputs.go_version }}

  create-unittest-issue:
    needs: [unit-tests]
    uses: hasAnybodySeenHarry/workflows/.github/workflows/create-issue.yaml@main
    if: failure()
    with:
      assignees: ${{ github.actor }}
      issue_template: .github/ACTIONS_ISSUE_TEMPLATES/unit_test_alert.md
      owner_repository: ${{ github.repository }}
      commit_hash: ${{ github.sha }}
      branch_name: ${{ github.ref_name }}

  close-unittest-issues:
    needs: [unit-tests]
    uses: hasAnybodySeenHarry/workflows/.github/workflows/close-issue.yaml@main
    with:
      issue_label: ${{ inputs.unittest_issue_label }}
      issue_title: ${{ inputs.unittest_issue_title }}

  static-analysis:
    uses: hasAnybodySeenHarry/workflows/.github/workflows/run-static-analysis.yaml@main
    with:
      go_version: ${{ inputs.go_version }}

  create-linting-issue:
    needs: [static-analysis]
    uses: hasAnybodySeenHarry/workflows/.github/workflows/create-issue.yaml@main
    if: failure()
    with:
      assignees: ${{ github.actor }}
      issue_template: .github/ACTIONS_ISSUE_TEMPLATES/static_analysis_alert.md
      owner_repository: ${{ github.repository }}
      commit_hash: ${{ github.sha }}
      branch_name: ${{ github.ref_name }}

  close-linting-issues:
    needs: [static-analysis]
    uses: hasAnybodySeenHarry/workflows/.github/workflows/close-issue.yaml@main
    with:
      issue_label: ${{ inputs.linting_issue_label }}
      issue_title: ${{ inputs.linting_issue_title }}

  validate-helm:
    uses: hasAnybodySeenHarry/workflows/.github/workflows/validate-helm-chart.yaml@main
    with:
      helm_version: ${{ inputs.helm_version }}
      helm_folder: ${{ inputs.helm_folder }}

  repo-meta:
    uses: hasAnybodySeenHarry/workflows/.github/workflows/gen-repo-meta.yaml@main

  containerize:
    needs: [unit-tests, static-analysis, validate-helm, repo-meta]
    uses: hasAnybodySeenHarry/workflows/.github/workflows/containerize.yaml@main
    with:
      image_tag: ${{ needs.repo-meta.outputs.image_tag }}
      repository_name: ${{ needs.repo-meta.outputs.repository_name }}
    secrets:
      docker_username: ${{ secrets.docker_username }}
      docker_password: ${{ secrets.docker_password }}

  sonar-analysis:
    runs-on: ubuntu-latest
    needs: [containerize]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonar_token }}

      - name: SonarQube Quality Gate
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        with:
          pollingTimeoutSec: 600
        env:
        SONAR_TOKEN: ${{ secrets.sonar_token }}

      - name: SonarQube Quality Gate check
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"

  package-helm:
    needs: [repo-meta, containerize]
    uses: hasAnybodySeenHarry/workflows/.github/workflows/package-helm-chart.yaml@main
    with:
      helm_version: ${{ inputs.helm_version }}
      helm_folder: ${{ inputs.helm_folder }}
      image_tag: ${{ needs.repo-meta.outputs.image_tag }}
      repository_name: ${{ needs.repo-meta.outputs.repository_name }}
      image_digest: ${{ needs.containerize.outputs.image_digest }}
    secrets:
      docker_username: ${{ secrets.docker_username }}
      helm_repo_url: ${{ secrets.helm_repo_url }}
      helm_repo_pat: ${{ secrets.helm_repo_pat }}
      helm_repo_target: ${{ secrets.helm_repo_target }}
      helm_repo_owner: ${{ secrets.helm_repo_owner }}
      helm_repo_name: ${{ secrets.helm_repo_name }}
