name: Validate Helm Chart
on:
  workflow_call:
    inputs:
      helm_version:
        required: true
        type: string
      helm_folder:
        required: true
        type: string
jobs:
  validate-helm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: ${{ inputs.helm_version }}

    - name: Lint Helm Chart
      run: |
        helm lint ./${{ inputs.helm_folder }}
